name: mypusht
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - tqdm
  - pip:
      - -e .[logging,teleop]
